AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Query projects

Parameters:
  ApiId:
    Type: String
  ProjectTableDataSourceName:
    Type: String

Resources:
  ProjectsQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: projects
      DataSourceName: !Ref ProjectTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/scan-all.vm
      ResponseMappingTemplateS3Location: ../vtl/return-scan-result.vm
