version: '3.7'

services:
  frontend:
    build: ./frontend
    working_dir: /app/redux-sample
    tty: true
    ports:
      - "82:5173"
    volumes:
      - './frontend:/app/redux-sample'
    command: bash -c "npm i && npm run dev"
  sam:
    build: ./sam
    working_dir: /sam/redux-sample
    ports:
      - '3000:3000'
    volumes:
      - './sam:/sam/redux-sample'
    env_file:
      - sam/.env
    command:
      - bash
      - -c
      - |
        echo "Launching aws-tools"
        sleep infinity
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: yaml
