AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync

Parameters:
  ProjectName:
    Type: String

Resources:
  # DynamoDB
  TablesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables.template.yaml
      Parameters:
        UserTableName: !Sub ${ProjectName}-user-table
        ProjectTableName: !Sub ${ProjectName}-project-table

  # ServiceRole
  ServiceRoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service-role.template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        UserTableArn: !GetAtt TablesStack.Outputs.UserTableArn
        ProjectTableArn: !GetAtt TablesStack.Outputs.ProjectTableArn

Outputs:
  ServiceRoleArn:
    Description: Write this value in samconfig.toml of 2.app-sync and start the stack
    Value: !GetAtt ServiceRoleStack.Outputs.ServiceRoleArn
