AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: redux-sample Schema

Parameters:
  ProjectName:
    Type: String
  ServiceRoleArn:
    Type: String
  ApiId:
    Type: String
  UserTableName:
    Type: String
  ProjectTableName:
    Type: String

Resources:
  # DataSource
  UserTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: UserTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref UserTableName
        AwsRegion: !Ref AWS::Region
  ProjectTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: ProjectTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref ProjectTableName
        AwsRegion: !Ref AWS::Region

#  # Relations
#  RelationsResolverStack:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: relations.template.yaml
#      Parameters:
#        ApiId: !Ref ApiId
#        UserTableDataSourceName: !GetAtt UserTableDataSource.Name
#        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

#  # Functions
#  FunctionsResolverStack:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: functions.template.yaml
#      Parameters:
#        ApiId: !Ref ApiId
#        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

  # mutation addProject
  MutationAddProjectStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/add-project.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

  # mutation addUser
  MutationAddUserStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/add-user.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name

  # mutation deleteProject
  MutationDeleteProjectStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/delete-project.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

  # mutation deleteUser
  MutationDeleteUserStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/delete-user.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name

  # mutation updateProject
  MutationUpdateProjectStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/update-project.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

  # mutation updateUser
  MutationUpdateUserStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/update-user.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name

  # query projects
  QueryProjectsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/projects.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        ProjectTableDataSourceName: !GetAtt ProjectTableDataSource.Name

  # query users
  QueryUsersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/users.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name
