AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: redux-sample Lambda DataClean

Parameters:
  ProjectName:
    Type: String
  UserTableName:
    Type: String
  ProjectTableName:
    Type: String
  SessionDataTableName:
    Type: String

Resources:
  DataClean:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/nodejs
      Handler: data-clean.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionName: !Sub ${ProjectName}-data-clean
      Description: redux-sample Data Clean
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectTableName
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTableName
          PROJECT_TABLE_NAME: !Ref ProjectTableName
      Events:
        ScheduleJob:
          Type: Schedule
          Properties:
            Name: !Sub ${ProjectName}-data-clean-schedule
            Schedule: cron(0 21 ? * 2 *)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - data-clean.ts

  AppSyncAuthorizerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DataClean}
      RetentionInDays: 3

