AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Mutation addSession

Parameters:
  ApiId:
    Type: String
  ProjectTableDataSourceName:
    Type: String

Resources:
  AddProjectMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: addProject
      DataSourceName: !Ref ProjectTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/put-item-project.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
