AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Mutation addUser

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  AddUserMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: addUser
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/put-item-user.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
