AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Mutation deleteProject

Parameters:
  ApiId:
    Type: String
  ProjectTableDataSourceName:
    Type: String

Resources:
  DeleteProjectMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: deleteProject
      DataSourceName: !Ref ProjectTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/delete-item-where-id-input-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
