AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Mutation updateUser

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  UpdateProjectMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updateUser
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "id" : $util.dynamodb.toDynamoDBJson($ctx.args.input.id)
          },
          "update" : {
            "expression" : "SET #name = :name, #password = :password",
            "expressionNames" : {
              "#name" : "name",
              "#password" : "password",
            },
            "expressionValues" : {
              ":name" : $util.dynamodb.toDynamoDBJson($ctx.args.input.name),
              ":password" : $util.dynamodb.toDynamoDBJson($ctx.args.input.password),
            }
          }
        }
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
